const { BasePage } = require('./BasePage');

class AddEmployeePage extends BasePage {
  constructor(page) {
    super(page);
    this.firstNameInput    = page.getByPlaceholder('First Name');
    this.middleNameInput   = page.getByPlaceholder('Middle Name');
    this.lastNameInput     = page.getByPlaceholder('Last Name');
    this.saveButton        = page.getByRole('button', { name: 'Save' });
    this.createLoginToggle = '.oxd-switch-input';
  }

  async goto() {
    await this.navigate('/web/index.php/pim/addEmployee');
    await this.waitForPageLoad();
  }

  async fillBasicInfo(employeeData) {
    await this.fill(this.firstNameInput, employeeData.firstName);
    if (employeeData.middleName) {
      await this.fill(this.middleNameInput, employeeData.middleName);
    }
    await this.fill(this.lastNameInput, employeeData.lastName);

    // Employee Id is auto-generated by OrangeHRM — just verify it has a value
    const autoId = await this.getEmployeeIdValue();
    if (!autoId) throw new Error('Employee Id was not auto-generated by OrangeHRM');
  }

  async enableLoginDetails() {
    const toggle = this.page.locator(this.createLoginToggle);
    const isChecked = await toggle.isChecked();
    if (!isChecked) {
      await toggle.click();
      await this.page.waitForTimeout(500);
    }
  }

  async fillLoginDetails(userData) {
    await this.enableLoginDetails();
    await this.page.waitForTimeout(500);

    const usernameInputs = this.page.locator('input[autocomplete="off"]');
    await usernameInputs.last().fill(userData.username);

    const passwordInputs = this.page.locator('input[type="password"]');
    await passwordInputs.first().fill(userData.password);
    await passwordInputs.last().fill(userData.password);
  }

  async addEmployee(employeeData, createLogin = false) {
    await this.fillBasicInfo(employeeData);

    if (createLogin && employeeData.username) {
      await this.fillLoginDetails(employeeData);
    }

    // Click Save and wait for the loading spinner to finish
    await this.click(this.saveButton);
    await this.wait.waitForSpinnerToDisappear(15000);
  }

  async getEmployeeIdValue() {
    const input = this.page.locator('.oxd-input-group:has(.oxd-label:has-text("Employee Id")) input');
    await input.waitFor({ state: 'visible', timeout: 5000 });
    return input.inputValue();
  }

  async isOnAddEmployeePage() {
    return this.page.url().includes('/pim/addEmployee');
  }
}

module.exports = { AddEmployeePage };
